baseurl         = "/"
theme           = "casper3"
languageCode    = "en-US"
paginate        = 6
googleAnalytics = "UA-113451260-1"
ignoreFiles = ["^public$"]
title       = "Alexander Bulimov's Models"
subtitle    = "Personal gallery"
copyright = '<br/><small><small>  <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="//i.creativecommons.org/l/by-sa/4.0/80x15.png"></a> Content licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>, except where indicated otherwise.</small></small>'

[params]

  description = "Just a small collection of scale models I've built."
  RSSLink = ""

  facebook = "https://www.facebook.com/abulimov"
  github = "https://github.com/abulimov"
  redditName = "abulimov"
  scalematesID = 38867

  # logo = "hugo-logo.png"
  orgName = "Alexander Bulimov"
  orgWebsite = "https://bulimov.me"

  author = "Alexander Bulimov"
  authorAvatar = "/images/pixel.png"
  authorLocation = "Dublin, Ireland"
  authorWebsite = "https://bulimov.me"
  authorDescription = "Amateur modelist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[permalinks]
  post = "/models/:slug/"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "Airplanes"
  url = "/categories/airplanes/"
  weight = 30

[[menu.main]]
  name = "Ships"
  url = "/categories/ships/"
  weight = 31

[[menu.main]]
  name = "Vehicles"
  url = "/categories/vehicles/"
  weight = 32

[[menu.main]]
  name = "IT Blog"
  url = "https://bulimov.me/"
  weight = 40
